name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: ./japan-transfer-site
      run: npm install
    
    - name: Build Tailwind CSS
      working-directory: ./japan-transfer-site
      run: npm run build
    
    - name: Copy files to root
      run: |
        cp japan-transfer-site/src/index.html ./
        cp -r japan-transfer-site/styles ./
        cp -r japan-transfer-site/scripts ./
        cp -r japan-transfer-site/public ./
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
